---
- name: Install nftables
  apt:
    name:
      - nftables
    state: present
  become: true
  tags: firewall

- name: Update Firewall config
  template:
    src: "nftables/{{ inventory_hostname }}.conf"
    dest: /etc/nftables.conf
    validate: "nft -c -f %s"
    owner: root
    group: root
    mode: 0755
  notify:
    - reload firewall
  become: true
  tags: firewall
