- name: Install nftables
  apt:
    name:
      - nftables
    state: present
  become: yes

- name: Update Firewall config
  template:
    src: "nftables/{{ inventory_hostname }}.conf"
    dest: /etc/nftables.conf
    validate: "nft -c -f %s"
  notify:
    - reload firewall
  become: yes
  tags: firewall