name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Ansible Lint
        run: ansible-lint .
        shell: bash
      - name: yamllint
        run: yamllint roles/ config.yml hosts.yml
        shell: bash